package com.vady.editor.gui;


public enum Property {
    INSTRUMENT_WIDTH,
    INSTRUMENT_HEIGHT,

    MAIN_WINDOW_TITLE,
    MAIN_WINDOW_WIDTH,
    MAIN_WINDOW_HEIGHT,

    SELECTION_BOX_LINE_WIDTH,
    SELECTION_BOX_LINE_COLOR_R,
    SELECTION_BOX_LINE_COLOR_G,
    SELECTION_BOX_LINE_COLOR_B,

    SCATCH_LINE_WIDTH,
    SCATCH_LINE_COLOR_R,
    SCATCH_LINE_COLOR_G,
    SCATCH_LINE_COLOR_B,
}
